# Workflow of JEE-Server

name: CI/CD

on:
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository access
        uses: actions/checkout@v2 # Check if the workflow can access our repo

      - name: Set up Java 11 environment
        uses: actions/setup-java@v1 # Sets up a Java environment
        with:
          java-version: 11

      - name: Test with Maven
        run: mvn test

  build-dev:
    needs: test
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build . --tag jee-api-sante:dev

  deploy-dev:
    needs: build-dev
    runs-on: self-hosted
    steps:
      - name: Stop previous Docker image
        run:  (docker stop jee-api-sante || echo "Container already stopped") && (docker rm jee-api-sante || echo "Image already removed")

      - name: Launch new Docker image
        env:
          OCR_TOKEN: ${{ secrets.OCR_TOKEN }}
        run: |
          docker run -d -p ${{ secrets.DEV_PORT }}:8080 -e OCR_TOKEN --name "jee-api-sante" jee-api-sante:dev

  deploy-prod:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Initliaze AWS env
        run: eb use ${{ secrets.AWS_ENVIRONMENT_NAME }}

      - name: Set env vars
        env:
          OCR_TOKEN: ${{ secrets.OCR_TOKEN }}
        run: eb setenv OCR_TOKEN=$OCR_TOKEN

      - name: Deploy on EB
        run: eb deploy ${{ secrets.AWS_ENVIRONMENT_NAME }}

